# Site
repository: ryanapking/ryanapking.github.io
# favicon: images/favicon.ico

# Personal info
name: Ryan Apking
title: JavaScript & PHP Developer
email: ryan.apking@gmail.com
#website: ryanapking.com

# Social links
#twitter_username: facespics
github_username:  ryanapking
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: ryanapking
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Ryan. I'm a developer, writer, and amateur woodworker. I love to build things, some of which you can check out below.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Rock climbing
#   - Gaming
#   - Knitting
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
#footer_show_references: true

# Build settings
remote_theme: ryanapking/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
